### ISSUE TITLE
yarn workspace is not supported

### ISSUE THREAD

**Issue by 7kms** [axetroy/vscode-npm-import-package-version#126]
in  [lerna monorepos](https://github.com/lerna/lerna), packages installed by `yarn install`. Runtime is ok, but the display is not installed.
![image](https://user-images.githubusercontent.com/12625342/82401866-8f17f680-9a8d-11ea-8386-93da9e31eedb.png)
the packages are hoisted in the root `node_modules/@types` folder

**Comment by axetroy** [comment]
I think I have solved this problem in the last update.

![截屏2021-03-15 14 39 06](https://user-images.githubusercontent.com/9758711/111113187-5e64f880-859c-11eb-8e2e-824740c21c0c.png)

If you still have this problem, feedback is welcome.
