### ISSUE TITLE
Causes issue with auto attach

### ISSUE THREAD

**Issue by JasCodes** [axetroy/vscode-npm-import-package-version#2]
My auto attach debugger gets hung after the debbuger encounter error, this only happens when you extension is installed, otherwise it works fine.

I can add video if you can't reproduce of something.

Thx.

**Comment by JasCodes** [comment]
@axetroy

**Comment by axetroy** [comment]
@jas99
I don't know how to reproduce it.

Can you describe it more clearly?

You can upload a gif image to help me found out the issue

**Comment by JasCodes** [comment]
Here it is.
https://www.youtube.com/watch?v=xCK4C_SmtSU

Let me know if smtg is unclear. 

And btw awesome extension. 😄 

Thx

**Comment by axetroy** [comment]
@jas99

I have watched the video and I am sorry about this.

I can not found how does it happen.

This extension should be unrelated to `auto attach` and `processes`.

They should not affect each other, but in fact, they do.

The only code related to the process

https://github.com/axetroy/vscode-npm-import-package-version/blob/6a64ed2678eceaa5ddef1d80de948a2c1601fa4f/src/utils.ts#L107

I am sorry. I can't fix this.

The source code is very simple to read, If you would like to, send me a PR

**Comment by JasCodes** [comment]
Thx for looking into it, I will look into it at some point in future; 

Thx

**Comment by axetroy** [comment]
@jas99 

hey guy.

I have released a new version, can you try it again or I will close this issue cause I can't do any help for you

**Comment by JasCodes** [comment]
Thx for getting back.. I am really short on time right now.. but will give it a go at some time.

Thx
