### ISSUE TITLE
ue shows the problem

### ISSUE THREAD

**Issue by xierenyuan** [axetroy/vscode-npm-import-package-version#41]
vscode version: `版本 1.36.1 (1.36.1)`
npm-import-package-version version: `0.6.1`

problem:

![image](https://user-images.githubusercontent.com/7599351/62457919-55038f80-b7ae-11e9-848c-57ae0eb8ee73.png)

期望正常显示

**Comment by axetroy** [comment]
![截屏2020-01-2001 35 21](https://user-images.githubusercontent.com/9758711/72685455-31968c00-3b25-11ea-9f66-50176521d9df.png)

问题无法复现，请尝试安装新版本试试
