### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chonthichayaver** [axetroy/vscode-npm-import-package-version#57]
- Issue Type: `Performance`
- Extension Name: `vscode-npm-import-package-version`
- Extension Version: `0.6.1`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.42.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Chonthicha Yaver\axetroy.vscode-npm-import-package-version-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by BannerBomb** [comment]
same here, my OS is Ubuntu 18.04.3 LTS x64
VSCode Version: November 2019 (version 1.41)
Extension Version: 0.6.1
[axetroy.vscode-npm-import-package-version-unresponsive.cpuprofile.txt](https://github.com/axetroy/vscode-npm-import-package-version/files/4008874/axetroy.vscode-npm-import-package-version-unresponsive.cpuprofile.txt)

**Comment by axetroy** [comment]
I am trying to solve this

The newly released version now uses LSP and uses C/S architecture.

Achieving segregation of progress may solve this problem
