### ISSUE TITLE
该扩展在 Windows 10 系统上不起作用

### ISSUE THREAD

**Issue by wtklbm** [axetroy/vscode-npm-import-package-version#91]
系统： Windows 10  2019 LTSC
VSCODE： 1.43

安装该扩展后，在 Windows 端是没有效果的（也就是在编写的 TS 文件中的 import 语句处没有版本号提示）。但我切换到 macOS系统，以同样的设置打开 macOS 中的 VSCODE，发现在 macOS 端是没有问题的。

**Comment by wtklbm** [comment]
退回到 0.6.1 版本时功能正常，望修正

**Comment by axetroy** [comment]
already fixed
